### ISSUE TITLE
Modify cli.py file

### ISSUE THREAD

**Issue by arsalanmstn** [SINTEF/pyopia#302] opened 2024-09-20 08:20 UTC
1- The "modify_config" function (line 39) is not handling the "pixel_size" change.

2- Subsequently, if one changes the raw file directory which contains .silc files, "raw-file" option does not work properly (line 64).  It seems that when we use --raw-files 'new_directory/*.silc', the pyopia modify-config command is interpreting the glob pattern 'new_directory/*.silc' as multiple unexpected arguments when expanded by the shell. 
*Suggestion: make the raw-file argument passed by the user as f-string at the end of line 64. 

3- Finally , some of the values in "steps" are not float objects, so "modify_value" must be revised (line 68).
*Suggestion: Add some logical condition may solve the problem

**Comment by nordam** [comment] 2024-09-20 09:10
Here is an example of how to accept multiple arguments for one command line option

https://typer.tiangolo.com/tutorial/multiple-values/options-with-multiple-values/

**Comment by emlynjdavies** [comment] 2024-09-20 17:41
duplicate of #307

**Closed by emlynjdavies** 2024-09-20 17:41 UTC
